require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'WorkifyApp' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  use_react_native!(:path => config["reactNativePath"])


  target 'WorkifyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'WorkifyApp-tvOS' do
  # Pods for WorkifyApp-tvOS

  target 'WorkifyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end